version: "2"
services:
  postgres:
    image: postgres:12.3
    restart: always
    container_name: cvlt-v.postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: cvlt
      POSTGRES_USER: cvlt
      POSTGRES_PASSWORD: X3GuqTAL
    volumes:
      - postgres-data-v:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    container_name: cvlt.adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 3308:8080
    links:
      - postgres
  redis:
    image: redis:3
    container_name: cvlt-v.redis
    ports:
      - 6380:6379
    logging:
      driver: none
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cvlt-v.redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:0
    ports:
      - 6381:8081
  nginx:
    image: nginx:mainline-alpine
    container_name: cvlt-v.nginx
    env_file:
      - .env
    volumes:
      - ./.extra/docker-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.extra/docker-nginx/node.conf:/etc/nginx/node.conf:ro
      - ./static:/var/www/html
    extra_hosts:
      - "localbox:${MACHINE_IP}"
    ports:
      - 83:80
volumes:
  postgres-data-v: